In [16]:
import pandas as pd
from narwhals import DataFrame

df = pd.DataFrame({
    "Person": ["A","B","B","C","C"],
    "Item": ["Idli","Idli","Dosa","Poha","Idli"],
    "1st Feb": [15,10,50,10,None],
    "2nd Feb": [20,None,50,20,10],
    "3rd Feb": [None,15,25,15,20],
    "4th Feb": [25,30,None,10,None],
    "5th Feb": [30,20,25,None,None],
    "6th Feb": [20,None,None,30,20],
    "7th Feb": [15,30,50,10,30]
})

In [17]:
df.head()

  Person  Item  1st Feb  2nd Feb  3rd Feb  4th Feb  5th Feb  6th Feb  7th Feb
0      A  Idli     15.0     20.0      NaN     25.0     30.0     20.0       15
1      B  Idli     10.0      NaN     15.0     30.0     20.0      NaN       30
2      B  Dosa     50.0     50.0     25.0      NaN     25.0      NaN       50
3      C  Poha     10.0     20.0     15.0     10.0      NaN     30.0       10
4      C  Idli      NaN     10.0     20.0      NaN      NaN     20.0       30

In [18]:
long_df = df.melt(
    id_vars=["Person", "Item"],
    var_name="Date",
    value_name="Quantity"
)

In [19]:
long_df.head()

  Person  Item     Date  Quantity
0      A  Idli  1st Feb      15.0
1      B  Idli  1st Feb      10.0
2      B  Dosa  1st Feb      50.0
3      C  Poha  1st Feb      10.0
4      C  Idli  1st Feb       NaN

In [31]:
long_df.fillna(0)

   Person  Item     Date  Quantity
0       A  Idli  1st Feb      15.0
1       B  Idli  1st Feb      10.0
2       B  Dosa  1st Feb      50.0
3       C  Poha  1st Feb      10.0
4       C  Idli  1st Feb       0.0
5       A  Idli  2nd Feb      20.0
6       B  Idli  2nd Feb       0.0
7       B  Dosa  2nd Feb      50.0
8       C  Poha  2nd Feb      20.0
9       C  Idli  2nd Feb      10.0
10      A  Idli  3rd Feb       0.0
11      B  Idli  3rd Feb      15.0
12      B  Dosa  3rd Feb      25.0
13      C  Poha  3rd Feb      15.0
14      C  Idli  3rd Feb      20.0
15      A  Idli  4th Feb      25.0
16      B  Idli  4th Feb      30.0
17      B  Dosa  4th Feb       0.0
18      C  Poha  4th Feb      10.0
19      C  Idli  4th Feb       0.0
20      A  Idli  5th Feb      30.0
21      B  Idli  5th Feb      20.0
22      B  Dosa  5th Feb      25.0
23      C  Poha  5th Feb       0.0
24      C  Idli  5th Feb       0.0
25      A  Idli  6th Feb      20.0
26      B  Idli  6th Feb       0.0
27      B  Dosa  6th Feb       0.0
28      C  Poha  6th Feb      30.0
29      C  Idli  6th Feb      20.0
30      A  Idli  7th Feb      15.0
31      B  Idli  7th Feb      30.0
32      B  Dosa  7th Feb      50.0
33      C  Poha  7th Feb      10.0
34      C  Idli  7th Feb      30.0